#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
노션 변형/엘리트 회차 → reading.json(레벨독해 L1~L4 세트) + bank.json(track=drill, id=var-*) 동시 생성.
변형 회차는 '지문 없는 영어 선지 종합문항'이라 reading 세트는 passages=[], 문항별 lead(인용)로 자기완결.
난도 매핑: 변형 1·2회=L1, 3회=L2, 4회=L3, 5회+엘리트=L4.

회차 데이터는 SETS 에 누적한다(노션에서 전사). 각 문항 = (유형, stem, lead, [선지5], 정답0base, 해설).
재실행 시 reading 의 L1~L4 세트와 bank 의 var-* 만 교체(L0·speed·cloze·qz·drl 보존).
"""
import json, os
from collections import Counter

BASE = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
READING = os.path.join(BASE, "data", "reading.json")
BANK = os.path.join(BASE, "data", "bank.json")

# 문항 유형 → drill group
GROUP = {"어휘": "어휘", "어법": "어법", "내용일치": "내용일치",
         "주제": "주제·요지", "지칭": "독해", "독해": "독해", "연결사": "연결사",
         "빈칸": "빈칸추론", "삽입": "순서·삽입", "순서": "순서·삽입"}

SETS = [
  {
    "set_id": "L1-13-1", "level": "L1", "unit": "올림포스 13강 변형",
    "source": "올림포스 13강 변형 1회 (★ 기초)",
    "title": "13강 변형 1회 · 어휘·어법·주제 종합 (★ 기초)",
    "items": [
      ("어휘", "다음 밑줄 친 단어와 의미가 가장 가까운 것은?",
       "We might forget an anecdote about a stranger because it makes few connections with our existing associations.",
       ["antidote", "statistic", "short story", "rumor", "argument"], 2,
       "anecdote는 '일화·짧은 이야기' = short story. ① antidote(해독제)는 철자가 비슷한 함정, ④ rumor는 본문의 gossip과 연결되는 함정."),
      ("어휘", "다음 밑줄 친 단어와 의미가 가장 가까운 것은?",
       "Steve Jobs used analogy to get people to embrace the new technology.",
       ["reject", "accept", "ignore", "criticize", "delay"], 1,
       "embrace는 '(기꺼이) 받아들이다' = accept. 반의어 ① reject가 최대 함정."),
      ("어휘", "다음 영영 풀이(English definition)에 해당하는 단어는?",
       "the psychological tendency to want something more strongly when we are deprived of it or when our freedom to choose it is taken away",
       ["attraction", "instinct", "scarcity", "reactance", "phenomenon"], 3,
       "'선택지를 빼앗기면 더 원하게 되는 심리'의 정의 → reactance. ③ scarcity(희소성)는 원인이지 현상명이 아니다."),
      ("어휘", "다음 밑줄 친 단어의 반의어로 가장 적절한 것은?",
       "The most effective communicators find ways to make the abstract personal.",
       ["concrete", "complex", "symbolic", "logical", "objective"], 0,
       "abstract(추상적)의 반의어 = concrete(구체적). 본문에서 abstract ↔ personal/concrete 대립."),
      ("어휘", "다음 밑줄 친 단어의 반의어로 가장 적절한 것은?",
       "If the process is fair, we cannot nearly as easily externalize the outcome.",
       ["realize", "generalize", "rationalize", "visualize", "internalize"], 4,
       "externalize(외부화)의 반의어 = internalize(내면화). 나머지 -ize 단어는 의미가 무관한 함정."),
      ("어휘", "다음 밑줄 친 단어의 반의어로 가장 적절한 것은?",
       "The idea of working in a virtual world was radically different.",
       ["digital", "physical", "artificial", "imaginary", "similar"], 1,
       "virtual(가상의)의 반의어 = physical(물리적·실물의). ④ imaginary는 virtual의 유의어에 가까워 반의어가 아니다."),
      ("내용일치", "대중음악과 접근성에 관한 글의 내용과 일치하는 것은?", "",
       ["Punk musicians insisted that their music be highly virtuosic.",
        "Ordinary people had never sung or made music before the popular music movement.",
        "The popular music movement was driven by a spirit of obedience.",
        "In the 1950s, anyone could pick up everyday objects and a second-hand guitar and start a band.",
        "Groups that had been excluded from music avoided opportunities to create."], 3,
       "본문과 일치(누구나 일상 도구·중고 기타로 밴드 시작). ① 펑크는 비기교적을 조건으로 삼아 반대, ② 보통 사람들은 늘 노래해 왔으므로 반대, ③ 저항(rebellion)이라 obedience는 반대, ⑤ 만끽했으므로 avoided는 반대."),
      ("내용일치", "포스터 실험(리액턴스)의 내용과 일치하는 것은?", "",
       ["The poster with the highest rating became unavailable.",
        "Students were promised that they could keep all the posters.",
        "Students were asked to arrange ten posters in order of attractiveness.",
        "After the change, students judged only the remaining nine posters.",
        "The unavailable poster was rated the least beautiful."], 2,
       "본문과 일치(포스터 10장을 매력도 순으로 배열). ① 사라진 건 1위가 아니라 3위, ② 보상은 1장, ④ 10장 전부 from scratch 재평가, ⑤ 사라진 포스터는 가장 아름다운 것으로 분류."),
      ("내용일치", "매몰 비용 오류에 관한 글의 내용과 일치하지 않는 것은?", "",
       ["People find it very difficult to walk away from investments that have not repaid them.",
        "Giving up would mean acknowledging that we have wasted something we cannot get back.",
        "Staying with a genuinely bad bet simply increases the amount we lose.",
        "The writer advises us to keep investing until it finally proves worthwhile.",
        "Sometimes we just have to cut our losses."], 3,
       "본문은 '손실을 끊어내라'고 주장. ④ '가치 있다 판명될 때까지 계속 투자하라'는 정반대(매몰비용 오류) → 불일치. 나머지는 본문 진술."),
      ("어법", "(A), (B), (C)의 각 네모 안에서 어법에 맞는 표현끼리 가장 적절하게 짝지은 것은?",
       "So if a new piece of information (A)(has / will have) something to do with us, it (B)(will be processed / will process) more easily and (C)(thoroughly / thorough).",
       ["has — will be processed — thoroughly", "has — will process — thoroughly",
        "has — will be processed — thorough", "will have — will be processed — thorough",
        "will have — will process — thoroughly"], 0,
       "(A) 조건 if절은 미래라도 현재시제 → has. (B) 정보가 '처리되는' 수동 → will be processed. (C) 동사 수식 부사 → thoroughly."),
      ("어법", "다음 빈칸에 어법상 가장 적절한 것은?",
       "Steve Jobs used analogy to get people ＿＿＿＿ the new technology.",
       ["embrace", "embracing", "embraced", "to be embraced", "to embrace"], 4,
       "get은 준사역동사로 get + O + to V. make/have/let(원형)과 달리 to부정사 → to embrace. ① embrace(원형)는 함정."),
      ("어법", "다음 빈칸에 어법상 가장 적절한 것은?",
       "All translators feel some pressure from the community of readers ＿＿＿＿ they are doing their work.",
       ["for who", "for whom", "whom", "which", "what"], 1,
       "do their work for the readers의 for가 관계사 앞으로 이동, 뒤가 완전한 절 → 전치사+관계대명사 for whom. ① for who 불가, ③ whom 단독은 전치사 누락."),
      ("주제", "자아와 기억에 관한 글의 주제로 가장 적절한 것은?", "",
       ["why people quickly forget gossip about their relatives",
        "the importance of memorizing statistics accurately",
        "how effective communicators make abstract ideas personal to engage the self",
        "the difficulty of taking a vacation away from home",
        "practical ways to lower the dropout rate of law schools"], 2,
       "주제 = '효과적인 의사전달자는 추상을 개인화해 자아를 일깨운다'. 나머지는 세부 소재를 과장한 함정."),
      ("주제", "매몰 비용 오류에 관한 글의 요지로 가장 적절한 것은?", "",
       ["We should sometimes stop and accept our losses rather than chase a bad investment.",
        "Persistence in any investment always pays off in the end.",
        "Emotional relationships are always more valuable than financial ones.",
        "Admitting our mistakes is unnecessary as long as we keep trying.",
        "The longer we hold an investment, the more worthwhile it becomes."], 0,
       "요지 = '나쁜 투자를 쫓지 말고 손실을 인정·단절하라'. ②⑤는 반대, ③④는 과장·왜곡."),
      ("주제", "Steve Jobs의 유추에 관한 글의 제목으로 가장 적절한 것은?", "",
       ["The Failure of the Virtual Workplace", "Why Physical Offices Will Never Disappear",
        "A Short History of Paper and Pens", "Steve Jobs's Long Struggle Against Analogy",
        "Familiar Terms Open the Door to New Technology"], 4,
       "친숙한 용어(document·folder·desktop)로 신기술 수용을 이끔 → 'Familiar Terms Open the Door to New Technology'."),
      ("주제", "공정한 과정의 역설에 관한 글의 제목으로 가장 적절한 것은?", "",
       ["How Unfair Processes Destroy Society", "The Hidden Cost of a Fair Process",
        "Winning Fair and Square Brings Pure Joy", "Always Blame Yourself for Every Outcome",
        "Consolation Prizes for Everyone"], 1,
       "공정한 과정이 결과 외부화를 막아 수용을 어렵게 하는 역설 → 'The Hidden Cost of a Fair Process'. ③은 정반대."),
      ("지칭", "다음 밑줄 친 This가 가리키는 것으로 가장 적절한 것은?",
       "This led to specific genres such as skiffle, but also, more generally, reflected a much more relaxed and inclusive attitude to music making.",
       ["the global circulation of music by the creative industries",
        "the punk movement that emerged in the 1970s",
        "the spirit of rebellion and freedom",
        "the fact that, in the 1950s, anyone could use everyday objects to start a band",
        "a sense of novelty and empowerment"], 3,
       "This는 앞 문장(1950년대 누구나 일상 도구로 밴드 시작)을 가리킴. ② 펑크는 This의 결과(뒤 문장)라 함정."),
      ("지칭", "다음 밑줄 친 it이 가리키는 것으로 가장 적절한 것은?",
       "In the end, by delaying the pain of admitting our problem, we only add to it.",
       ["the pain", "our problem", "the investment", "the relationship", "a thousand dollars"], 0,
       "add to it의 it은 앞의 the pain. ② our problem은 지칭 함정 — 미루는 것은 '고통'이지 '문제'가 아니다."),
      ("연결사", "다음 빈칸에 들어갈 연결어로 가장 적절한 것은?",
       "We have been thinking about ourselves in our whole lives. ＿＿＿＿ if a new piece of information has something to do with us, it will be more easily and thoroughly processed.",
       ["However", "Nevertheless", "In contrast", "For example", "So"], 4,
       "앞(평생 자신을 생각)의 결과로 뒤(나와 관련된 정보는 더 잘 처리)가 이어짐 → 인과·결과의 So."),
      ("연결사", "다음 빈칸에 들어갈 연결어로 가장 적절한 것은?",
       "We may reassure ourselves by believing that our bad outcome had everything to do with the unfair process. If the process is fair, ＿＿＿＿, we cannot nearly as easily externalize the outcome.",
       ["therefore", "similarly", "however", "for instance", "moreover"], 2,
       "앞(불공정→외부 귀인으로 자기 안심)과 뒤(공정→외부화 불가)가 대조 → 역접 however."),
    ],
  },
  {
    "set_id": "L1-13-2", "level": "L1", "unit": "올림포스 13강 변형",
    "source": "올림포스 13강 변형 2회 (★★ 적용)",
    "title": "13강 변형 2회 · 어휘·어법·빈칸·순서 종합 (★★ 적용)",
    "items": [
      ("어휘", "다음 글에서 밑줄 친 (a)~(e) 중 문맥상 낱말의 쓰임이 적절하지 않은 것은?",
       "While ordinary people had always sung, the popular music movement was driven by a spirit of (a)rebellion and freedom. Punk musicians made it a condition for their music to be non-virtuosic and (b)accessible to all. This reflected a much more relaxed and (c)exclusive attitude to music making. Groups who had been entirely (d)excluded from music revelled in opportunities to create, leading to a sense of (e)novelty and empowerment.",
       ["(a)", "(b)", "(c)", "(d)", "(e)"], 2,
       "(c) exclusive(배타적)가 문맥상 틀림 → inclusive(포용적)이어야. 저항·자유·모두에게 열린 흐름상 (a)rebellion·(b)accessible·(d)excluded·(e)novelty는 적절."),
      ("어휘", "다음 글에서 밑줄 친 (a)~(e) 중 문맥상 낱말의 쓰임이 적절하지 않은 것은?",
       "If we have invested in something that hasn't (a)repaid us, we find it very difficult to walk away. This is the sunk cost (b)fallacy. Our instinct is to continue investing as we hope our investment will prove to be (c)worthwhile. But if something really is a bad bet, staying with it simply (d)reduces the amount we lose. Sometimes we just have to (e)cut our losses.",
       ["(a)", "(b)", "(c)", "(d)", "(e)"], 3,
       "(d) reduces(줄인다)가 틀림 → increases. 나쁜 투자를 고수하면 손실은 늘어난다. 나머지는 적절."),
      ("어휘", "다음 영영 풀이(English definition)에 해당하는 표현은?",
       "to make use of a supply of something, such as knowledge or resources, that is available to you",
       ["draw on", "set about", "refer to", "arrive at", "consist of"], 0,
       "'이용 가능한 지식·자원을 활용하다' = draw on(= rely on, make use of). ③ refer to(참고하다)는 의미가 가까워 보이는 최대 함정."),
      ("어법", "다음 글의 밑줄 친 부분 (a)~(e) 중 어법상 틀린 것은?",
       "There is one complex network that (a)is larger and quicker to access than all others. We have been thinking about (b)ourselves in our whole lives. So if a new piece of information has something to do with us, it will (c)be processed more easily. The most effective communicators find ways to make the abstract (d)personal. Hearing that the dropout rate is 33% (e)are an abstract statistic.",
       ["(a)", "(b)", "(c)", "(d)", "(e)"], 4,
       "동명사구 주어(Hearing …)는 단수 취급 → (e)are가 아니라 is. 나머지 (a)~(d)는 적절."),
      ("어법", "다음 글의 밑줄 친 부분 (a)~(e) 중 어법상 틀린 것은?",
       "In one study, students were asked (a)to arrange ten posters in order of attractiveness, with the agreement (b)which afterward they could keep one poster as a reward. Five minutes later, they were told that the poster with the third highest rating was no longer (c)available. Then they were asked to judge all ten (d)from scratch. The poster that was no longer available was suddenly (e)classified as the most beautiful.",
       ["(a)", "(b)", "(c)", "(d)", "(e)"], 1,
       "the agreement 뒤는 완전한 절이므로 관계사 (b)which가 아니라 동격 that이 되어야 한다. 나머지는 적절."),
      ("어법", "다음 글의 밑줄 친 부분 (a)~(e) 중 어법상 틀린 것은?",
       "Giving up would (a)mean acknowledging that we have wasted something we can't get back. The problem is that if something really is a bad bet, then (b)staying with it simply (c)increase the amount we lose. Rather than (d)walk away from a bad five-year relationship, we turn it into a bad 10-year one. In the end, by (e)delaying the pain, we only add to it.",
       ["(a)", "(b)", "(c)", "(d)", "(e)"], 2,
       "동명사 주어 staying with it은 단수 → (c)increase가 아니라 increases. (b)staying(동명사 주어)·(d)walk(rather than 뒤 원형 병렬)은 적절."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "These are all side issues; the attraction is that they are ＿＿＿＿.",
       ["in short supply", "widely available", "highly practical", "easy to replace", "free of charge"], 0,
       "수집품의 매력은 '공급이 부족하다'는 데 있다(주제문). ② widely available은 정반대."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "The explosion of popular music in the second half of the twentieth century propelled a new understanding of ＿＿＿＿ in relation to music.",
       ["accessibility", "difficulty", "exclusivity", "tradition", "profitability"], 0,
       "첫 문장의 키워드 accessibility. ③ exclusivity는 정반대 함정."),
      ("빈칸", "다음 빈칸 (A), (B)에 들어갈 말로 가장 적절하게 짝지은 것은?",
       "We may reassure ourselves by believing that our bad outcome had (A)＿＿＿ to do with us and (B)＿＿＿ to do with the unfair process.",
       ["(A) little — (B) everything", "(A) everything — (B) little", "(A) much — (B) nothing", "(A) nothing — (B) little", "(A) something — (B) anything"], 0,
       "나쁜 결과는 '나와 거의 무관(little)·불공정한 과정과 전적으로 관련(everything)'이라는 대구 병렬."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "Steve Jobs understood that using ＿＿＿＿ would make the new technology easier to understand.",
       ["familiar terms", "complex codes", "foreign words", "technical jargon", "abstract symbols"], 0,
       "친숙한 용어가 신기술 이해를 쉽게 만든다(요지 직결)."),
      ("연결사", "다음 빈칸 (A), (B)에 들어갈 연결어로 가장 적절한 것은?",
       "The attraction is that they are in short supply. (A)＿＿＿, students were asked to arrange ten posters, and one was later made unavailable. (B)＿＿＿, that poster was suddenly classified as the most beautiful.",
       ["(A) In one study — (B) As a result", "(A) For instance — (B) However", "(A) In contrast — (B) Therefore", "(A) In one study — (B) Nevertheless", "(A) By contrast — (B) As a result"], 0,
       "(A) 실험 도입(In one study), (B) 조작에 따른 결과(As a result)."),
      ("연결사", "다음 빈칸 (A), (B)에 들어갈 연결어로 가장 적절한 것은?",
       "Translators always draw on more than one source text. (A)＿＿＿ the scene of translation consists of just one person with a pen and paper, that person's linguistic knowledge arises from lots of other texts. (B)＿＿＿, his or her idea of the translation's purpose will be influenced by the expectations of the readers.",
       ["(A) Even when — (B) Moreover", "(A) Because — (B) However", "(A) Even when — (B) Nevertheless", "(A) Unless — (B) Therefore", "(A) While — (B) In contrast"], 0,
       "(A) '~일 때조차도'(양보) Even when, (B) 두 번째 근거 추가(연속) Moreover."),
      ("내용일치", "Alexander Pope의 번역에 관한 내용과 일치하는 것은?", "",
       ["Pope had pretty good Greek but did not translate the Iliad entirely on his own.",
        "Pope refused to use any existing translations.",
        "Pope translated the Iliad without using any dictionaries.",
        "There were no earlier translations in Latin or French.",
        "Pope worked completely alone with no commentaries."], 0,
       "Pope는 그리스어를 꽤 잘했지만 혼자 번역하지 않고 주석·기존 번역본·사전을 활용했다. 나머지는 본문과 반대."),
      ("내용일치", "가상 작업 공간의 명명에 관한 내용과 일치하는 것은?", "",
       ["Ideas written on paper were called a document.",
        "Documents that needed storing were placed directly on a desk.",
        "Folders were kept inside documents.",
        "The word 'desktop' replaced the word 'folder'.",
        "Steve Jobs avoided using familiar physical-world terms."], 0,
       "종이에 쓴 생각 = document. ② 문서는 folder에, folder는 desk에 보관되므로 반대 구조. ④⑤도 불일치."),
      ("삽입", "글의 흐름으로 볼 때, 주어진 문장이 들어가기에 가장 적절한 곳은?",
       "〈주어진 문장〉 This is the sunk cost fallacy. ── ( ① ) If we've invested in something that hasn't repaid us, we find it very difficult to walk away. ( ② ) Our instinct is to continue investing as we hope our investment will prove to be worthwhile in the end. ( ③ ) Giving up would mean acknowledging that we've wasted something we can't get back. ( ④ ) The problem is that staying with a bad bet simply increases the amount we lose. ( ⑤ )",
       ["①", "②", "③", "④", "⑤"], 0,
       "'This is the sunk cost fallacy'는 첫 문장(투자를 떠나지 못함)을 요약하므로 그 직후 ①."),
      ("삽입", "글의 흐름으로 볼 때, 주어진 문장이 들어가기에 가장 적절한 곳은?",
       "〈주어진 문장〉 Or at least, it seemed radically different. ── Before computers, people worked in a physical world. ( ① ) We used paper and pens and physical file folders and so on. ( ② ) The idea of working in a virtual world was radically different. ( ③ ) What Jobs understood was that a physical office was fundamentally similar to a virtual office. ( ④ ) To win over the masses, he drew strong analogies between the two. ( ⑤ )",
       ["①", "②", "③", "④", "⑤"], 2,
       "'Or at least, it seemed radically different'는 'was radically different'를 수사적으로 정정하므로 그 직후 ③."),
      ("순서", "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
       "In the pre-computer workplace, the names of things came from physical objects. (A) When those documents needed to be stored, they were put in a folder. (B) When ideas were written on paper, it was called a document. (C) And those folders were kept on a desk.",
       ["(B) — (A) — (C)", "(A) — (B) — (C)", "(B) — (C) — (A)", "(C) — (A) — (B)", "(A) — (C) — (B)"], 0,
       "생각을 적음=document(B) → 보관=folder(A) → folder를 desk에(C) 순으로 위계가 이어진다."),
      ("순서", "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
       "In one study, students were asked to arrange ten posters in order of attractiveness. (A) Five minutes later, they were told that the poster with the third highest rating was no longer available. (B) The poster that was no longer available was suddenly classified as the most beautiful. (C) Then they were asked to judge all ten from scratch.",
       ["(A) — (C) — (B)", "(A) — (B) — (C)", "(C) — (A) — (B)", "(B) — (A) — (C)", "(C) — (B) — (A)"], 0,
       "5분 후 통보(A) → 처음부터 재평가(C) → 사라진 포스터가 1위로 분류(B)."),
      ("주제", "대중음악과 접근성에 관한 글의 제목으로 가장 적절한 것은?", "",
       ["How Accessibility Opened Up Music to Everyone", "The Decline of Professional Musicianship",
        "Skiffle: The Greatest Genre of the 1950s", "Why Punk Music Failed to Last",
        "The Economics of the Creative Industries"], 0,
       "접근성이 음악을 모두에게 열었다는 요지 → 'How Accessibility Opened Up Music to Everyone'. 나머지는 세부 소재 과장."),
      ("주제", "희소성과 리액턴스에 관한 글의 주제로 가장 적절한 것은?", "",
       ["why we find things more attractive when they become scarce or unavailable",
        "how collectors determine the fair price of rare items",
        "the practical uses of stamps, coins, and vintage cars",
        "the design of psychological experiments using posters",
        "why people generally prefer abundant options to limited ones"], 0,
       "희소·제거될 때 더 매력적으로 여긴다는 리액턴스. ⑤ '풍부한 선택을 선호'는 정반대."),
    ],
  },
  {
    "set_id": "L2-13-3", "level": "L2", "unit": "올림포스 13강 변형",
    "source": "올림포스 13강 변형 3회 (★★★ 심화)",
    "title": "13강 변형 3회 · 어법복합·핵심빈칸·함의·무관문장 (★★★ 심화)",
    "items": [
      ("어법", "다음 빈칸에 어법상 가장 적절한 것은?",
       "＿＿＿ outraging as the combination of an unfavorable outcome and an unfair process is, this combination also brings with it a consolation prize.",
       ["As", "So", "However", "Though it", "Despite"], 0,
       "As + 형용사 + as + S + V '~이긴 하지만'의 양보 도치. 보어 outraging이 앞으로 이동하고 맨 뒤에 is가 남는다. 단순 비교 '~만큼'으로 오독하면 안 된다."),
      ("어법", "다음 빈칸에 어법상 가장 적절한 것은?",
       "Punk musicians made ＿＿＿ a condition for their music to be non-virtuosic and accessible to all.",
       ["it", "that", "them", "which", "what"], 0,
       "make + it(가목적어) + a condition + for … to V(진목적어) 구조 → 가목적어 it이 필요하다."),
      ("어법", "다음 빈칸에 어법상 가장 적절한 것은?",
       "When those documents needed ＿＿＿＿, they were put in a folder.",
       ["to be stored", "to store", "storing", "stored", "being stored"], 0,
       "문서는 '보관되는' 대상이므로 need to be p.p.(수동 부정사) → to be stored. to store(능동)는 함정."),
      ("어휘", "다음 밑줄 친 단어와 의미가 가장 가까운 것은?",
       "A new piece of information that has to do with us will be more easily and thoroughly processed.",
       ["completely", "superficially", "rarely", "briefly", "carelessly"], 0,
       "thoroughly = '철저하게·완전히' = completely, fully. ② superficially(피상적으로)는 반의어 함정."),
      ("어휘", "다음 영영 풀이(English definition)에 해당하는 단어는? (본문의 bad bet 참고)",
       "a risky choice or course of action taken in the hope that it will bring a good result",
       ["bet", "venture", "instinct", "reward", "fallacy"], 0,
       "'좋은 결과를 바라며 위험을 감수한 선택' = bet. ② venture는 의미가 가까운 함정이나 정의문은 bet에 더 가깝다."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "There is one complex network that is larger and quicker to access than all others — ＿＿＿＿.",
       ["the self", "the brain", "the memory", "society", "the community"], 0,
       "가장 크고 빠른 네트워크 = 자아(the self). 지문 전체의 핵심 개념."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "The tendency to stay with an investment that hasn't repaid us is known as the ＿＿＿＿.",
       ["sunk cost fallacy", "consolation prize", "crowd translation", "reactance effect", "retention rate"], 0,
       "보답하지 않는 투자를 고수하는 성향 = 매몰 비용 오류. 나머지는 다른 지문 핵심어로 구성된 크로스 함정."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "In both these senses every translation is a ＿＿＿＿ translation.",
       ["crowd", "solitary", "literal", "free", "machine"], 0,
       "두 가지 의미에서 모든 번역은 군중 번역(crowd translation). ② solitary는 정반대."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "This led to a sense of ＿＿＿＿ in and beyond the music sphere.",
       ["novelty and empowerment", "order and tradition", "fear and exclusion", "profit and competition", "silence and isolation"], 0,
       "접근성 확대 → 참신함과 자율성(novelty and empowerment). 나머지 짝은 본문과 반대되거나 무관."),
      ("삽입", "글의 흐름으로 볼 때, 주어진 문장이 들어가기에 가장 적절한 곳은?",
       "〈주어진 문장〉 Five minutes later, they were told that the poster with the third highest rating was no longer available. ── In one study, students were asked to arrange ten posters in order of attractiveness, with the agreement that afterward they could keep one as a reward. ( ① ) Then they were asked to judge all ten from scratch. ( ② ) The poster that was no longer available was suddenly classified as the most beautiful. ( ③ ) In psychology, this phenomenon is called reactance. ( ④ ) When we are deprived of an option, we suddenly deem it more attractive. ( ⑤ )",
       ["①", "②", "③", "④", "⑤"], 0,
       "'5분 후 통보' 문장은 포스터 배열 직후·재평가 이전이므로 ①에 들어간다."),
      ("삽입", "글의 흐름으로 볼 때, 주어진 문장이 들어가기에 가장 적절한 곳은?",
       "〈주어진 문장〉 Translators always draw on more than one source text. ── The English poet Alexander Pope had pretty good Greek, but when he set about translating Homer's Iliad he was not on his own. ( ① ) He had Greek commentaries to refer to, and translations that had already been done in English, Latin, and French. ( ② ) Even when the scene of translation consists of just one person with a pen and paper, that person's linguistic knowledge arises from lots of other texts. ( ③ ) And then his or her idea of the translation's purpose will be influenced by the expectations of the readers. ( ④ ) In both these senses, every translation is a crowd translation. ( ⑤ )",
       ["①", "②", "③", "④", "⑤"], 1,
       "'Translators always draw on more than one source text'는 Pope 사례(주석·기존 번역본 활용) 뒤의 일반화이므로 ②에 들어간다."),
      ("순서", "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
       "The most effective communicators find ways to make the abstract personal. (A) Hearing that \"the first-year dropout rate is 33%\" is an abstract statistic. (B) Consider the warning that law schools give to motivate first-year students about the rigors of their program. (C) But \"One of the three of you won't be joining us next fall\" wakes up the self.",
       ["(B) — (A) — (C)", "(A) — (B) — (C)", "(B) — (C) — (A)", "(C) — (A) — (B)", "(A) — (C) — (B)"], 0,
       "사례 도입(B) → 추상 통계(A) → 자아를 깨우는 말(C) 순."),
      ("순서", "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
       "The explosion of popular music propelled a new understanding of accessibility. (A) This led to genres such as skiffle and reflected a much more relaxed and inclusive attitude. (B) Suddenly, in the 1950s, anyone could pick up everyday objects and a second-hand guitar and start a band. (C) This approach later led to the punk movement of the 1970s, open to all.",
       ["(B) — (A) — (C)", "(A) — (B) — (C)", "(B) — (C) — (A)", "(C) — (B) — (A)", "(A) — (C) — (B)"], 0,
       "1950년대 시작(B) → 스키플·포용적 태도(A) → 1970년대 펑크(C) 연대순."),
      ("어법", "(A)의 어법과 (B) term의 문맥상 의미로 가장 적절하게 짝지은 것은?",
       "(A)(What / That) Jobs understood was that a physical office was fundamentally similar to a virtual office. He knew that using familiar (B)terms would make the new technology easier to understand.",
       ["What — words/expressions", "That — words/expressions", "What — semesters", "That — conditions", "What — periods"], 0,
       "(A) understood의 목적어 자리가 비어 있으므로 선행사를 포함한 관계대명사 What. (B) term = '용어'(words/expressions) — 학기·조건은 함정."),
      ("어법", "(A)의 어법과 (B)에 들어갈 문맥상 적절한 단어로 가장 적절하게 짝지은 것은?",
       "If we've invested in something that hasn't repaid us — (A)(be it / is it) money in a failing venture, or time in an unhappy relationship — we hope it will prove to be (B)＿＿＿ in the end.",
       ["be it — worthwhile", "is it — worthwhile", "be it — worthless", "is it — worthless", "being it — worthwhile"], 0,
       "(A) whether it be의 양보 도치 be it. (B) 결국 가치 있을 것이라는 희망이므로 worthwhile. worthless는 반대."),
      ("내용일치", "자아와 기억(로스쿨 경고)에 관한 진술 중 올바른(True) 것은?", "",
       ["\"One of the three of you won't be joining us next fall\" is meant to wake up the self.",
        "\"The dropout rate is 33%\" is described as a personal, vivid message.",
        "Law schools give the warning to discourage students from studying.",
        "The abstract statistic is said to be more effective than the personal message.",
        "The self is described as the smallest and slowest network of all."], 0,
       "'셋 중 한 명은 내년에 없다'는 말이 자아를 깨운다(참). ② 통계는 추상적, ③ 동기 부여가 목적, ④ 개인화 메시지가 더 효과적, ⑤ 자아는 가장 크고 빠른 네트워크 → 모두 거짓."),
      ("내용일치", "포스터 실험에 관한 진술 중 올바른(True) 것은?", "",
       ["It was the third-ranked poster, not the top one, that was made unavailable.",
        "Students re-ranked only the nine remaining posters.",
        "The removed poster was judged the least attractive afterward.",
        "Students received ten posters as a reward for participating.",
        "The study disproved the idea of reactance."], 0,
       "제거된 건 1위가 아니라 3위 포스터(참). ② 10장 전부 재평가, ③ 제거된 포스터가 가장 아름다움, ④ 보상은 1장, ⑤ 실험은 리액턴스를 입증 → 모두 거짓."),
      ("연결사", "다음 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?",
       "This led to specific genres such as skiffle, (A)＿＿＿, (B)＿＿＿, reflected a much more relaxed and inclusive attitude to music making.",
       ["(A) but also — (B) more generally", "(A) and so — (B) in particular", "(A) however — (B) for example", "(A) but also — (B) for instance", "(A) therefore — (B) in short"], 0,
       "not only ~ but also의 변형(led to ~ but also … reflected) + more generally(더 일반적으로)."),
      ("독해", "다음 밑줄 친 seemed가 함의하는 바로 가장 적절한 것은?",
       "The idea of working in a virtual world was radically different. Or at least, it seemed radically different.",
       ["In reality, the virtual and physical worlds were not so different after all.",
        "The virtual world was completely impossible to understand.",
        "People never accepted the idea of a virtual world.",
        "The physical world was actually superior to the virtual one.",
        "Jobs failed to notice any similarity between the two worlds."], 0,
       "was → seemed로 정정한 것은 '실제로는 그리 다르지 않았다'는 반전 복선 → ①."),
      ("독해", "다음 글에서 전체 흐름과 관계 없는 문장은?",
       "Steve Jobs used analogy to get people to embrace the new technology. ① Before computers, people worked in a physical world using paper, pens, and file folders. ② What Jobs understood was that a physical office was fundamentally similar to a virtual office. ③ Modern smartphones now contain more computing power than the spacecraft of the early space age. ④ So he drew strong analogies between the familiar workplace and the new virtual one. ⑤ Documents, folders, and desktops are the terms we use because of this insight.",
       ["①", "②", "③", "④", "⑤"], 2,
       "스마트폰의 계산 능력(③)은 유추를 통한 신기술 수용이라는 전체 흐름과 무관한 문장이다."),
    ],
  },
  {
    "set_id": "L3-13-4", "level": "L3", "unit": "올림포스 13강 변형",
    "source": "올림포스 13강 변형 4회 (★★★★ 함정)",
    "title": "13강 변형 4회 · 추론빈칸·통합크로스·요약 (★★★★ 함정)",
    "items": [
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "Information about the self is processed more easily because ＿＿＿＿.",
       ["the self is the largest and quickest network to access", "statistics are always easier to memorize",
        "strangers make more connections than we do", "gossip is something we are bound to forget",
        "abstract ideas are naturally more vivid"], 0,
       "자아는 가장 크고 빠르게 접근되는 네트워크이므로 자아 관련 정보가 더 쉽게 처리된다."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "A fair process can be a hidden cost because ＿＿＿＿.",
       ["it prevents us from blaming external factors for a bad outcome", "it always guarantees a pleasant result",
        "it removes any sense of personal responsibility", "it makes the final outcome completely irrelevant",
        "it offers a generous consolation prize to losers"], 0,
       "공정한 과정은 나쁜 결과를 외부 탓으로 돌리지 못하게 만들어 위안을 빼앗는다."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "Even a solitary translator's work is shaped by other texts, which is why every translation is best understood as ＿＿＿＿.",
       ["a collective, crowd-based act", "a purely individual creation", "an essentially impossible task",
        "a word-for-word transfer", "a fully mechanical process"], 0,
       "혼자 하는 번역도 다른 텍스트의 영향을 받으므로 '집단적·군중적 행위'. ② 순수 개인 창작은 정반대."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "The popular music movement showed that music making could be ＿＿＿＿ rather than reserved for trained professionals.",
       ["open to everyone", "strictly commercial", "technically demanding", "limited to elites", "purely traditional"], 0,
       "대중음악 운동은 음악이 전문가의 전유물이 아니라 '모두에게 열릴' 수 있음을 보였다."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "Reactance explains why, when an option is taken away, we suddenly ＿＿＿＿ it more desirable.",
       ["deem", "deny", "dismiss", "doubt", "delay"], 0,
       "deem = '(~로) 여기다'. 선택권이 박탈되면 더 바람직하게 '여긴다'는 리액턴스 개념어."),
      ("어휘", "다음 빈칸에 문맥상 가장 적절한 것은?",
       "We turn a bad five-year relationship into a bad 10-year one rather than ＿＿＿＿ our losses.",
       ["cutting", "curing", "casting", "costing", "counting"], 0,
       "cut one's losses('손절하다'). cure·cast·cost·count는 형태가 비슷한 철자 함정."),
      ("어휘", "다음 영영 풀이(English definition)에 해당하는 단어는?",
       "something that makes you feel a little better when you are disappointed or have lost something",
       ["consolation", "compensation", "reaction", "obligation", "celebration"], 0,
       "'실망·상실 때 위안이 되는 것' = consolation(prize). ② compensation('보상')은 최대 함정."),
      ("어법", "다음 글의 밑줄 친 부분 (a)~(e) 중 어법상 틀린 것은?",
       "All translators feel some pressure from the community of readers for whom they are (a)doing their work. Even when the scene of translation consists of just one person (b)sitting with a pen and paper, that person's linguistic knowledge (c)arise from lots of other texts. (d)Influenced by the expectations of readers, the translator shapes the work. In both senses every translation is (e)a crowd translation.",
       ["(a)", "(b)", "(c)", "(d)", "(e)"], 2,
       "주어 knowledge는 단수 → (c)arise가 아니라 arises. 나머지는 적절."),
      ("어법", "다음 글의 밑줄 친 부분 (a)~(e) 중 어법상 틀린 것은?",
       "What Jobs understood was (a)that a physical office was similar to a virtual one. He used analogy to get people (b)to embrace the new technology. The familiar terms (c)that we use — documents, folders, desktops — (d)is drawn from the physical world, (e)making the new technology easier to grasp.",
       ["(a)", "(b)", "(c)", "(d)", "(e)"], 3,
       "주어 The familiar terms는 복수 → (d)is가 아니라 are drawn. (a)that(보어절)·(c)that(관계사)는 적절."),
      ("독해", "다음 밑줄 친 부분이 의미하는 바로 가장 적절한 것은?",
       "In the end, by delaying the pain of admitting our problem, we only add to it.",
       ["Postponing the decision makes our eventual loss even greater.", "Admitting the problem solves it immediately.",
        "The pain disappears if we simply wait long enough.", "Investing more always reduces our suffering.",
        "Time heals every bad investment in the end."], 0,
       "결정을 미루면 결국 손실이 더 커진다는 뜻. 나머지는 본문과 반대."),
      ("독해", "다음 밑줄 친 부분이 의미하는 바로 가장 적절한 것은?",
       "The popular music movement reflected a much more relaxed and inclusive attitude to music making.",
       ["Music making became open and welcoming to all kinds of people.", "Musicians stopped caring about the quality of their music.",
        "Only trained professionals were allowed to perform.", "Traditional genres disappeared entirely.",
        "Music became more commercial and competitive."], 0,
       "inclusive = '포용적·모두에게 열린'. ② 품질을 등한시했다는 과장 함정."),
      ("순서", "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
       "When we receive an unfavorable outcome through an unfair process, we can reassure ourselves. (A) If the process is fair, however, we cannot externalize the outcome so easily. (B) We believe the bad outcome had little to do with us and everything to do with the unfairness. (C) This is the hidden cost of a fair process.",
       ["(B) — (A) — (C)", "(A) — (B) — (C)", "(B) — (C) — (A)", "(C) — (A) — (B)", "(A) — (C) — (B)"], 0,
       "외부 귀인으로 안심(B) → 공정하면 그럴 수 없음(A) → 그것이 숨겨진 비용(C)."),
      ("삽입", "글의 흐름으로 볼 때, 주어진 문장이 들어가기에 가장 적절한 곳은?",
       "〈주어진 문장〉 But this was about more than just new genres. ── Suddenly anyone could pick up everyday objects and start a band. ( ① ) This led to specific genres such as skiffle. ( ② ) It reflected a much more relaxed and inclusive attitude to music making. ( ③ ) Groups previously excluded from music revelled in new opportunities to create. ( ④ ) This led to a sense of novelty and empowerment. ( ⑤ )",
       ["①", "②", "③", "④", "⑤"], 1,
       "'But this was about more than just new genres'는 'skiffle 같은 장르' 뒤, '태도' 설명 앞인 ②에 들어간다."),
      ("독해", "다음 글에서 전체 흐름과 관계 없는 문장은?",
       "People are strongly attracted to things that are scarce. ① In one study, students ranked ten posters and one was made unavailable. ② The unavailable poster was suddenly rated the most beautiful. ③ In psychology, this phenomenon is called reactance. ④ Collecting stamps and coins can be an expensive but rewarding lifelong hobby. ⑤ When our freedom to choose is removed, we want the thing all the more.",
       ["①", "②", "③", "④", "⑤"], 3,
       "우표·동전 수집 취미의 비용(④)은 리액턴스라는 흐름과 무관한 문장이다."),
      ("주제", "다음 두 글(리액턴스, 매몰 비용 오류)이 공통적으로 시사하는 바로 가장 적절한 것은?", "",
       ["Human decisions are often driven by irrational psychological biases rather than objective value.",
        "People always weigh costs and benefits in a fully rational way.",
        "Scarcity and past investment have no effect on our judgment.",
        "Emotional attachment generally improves financial decisions.",
        "We tend to undervalue things that are hard to obtain."], 0,
       "두 글 모두 객관적 가치보다 비합리한 심리적 편향이 결정을 이끈다는 점을 공유한다."),
      ("주제", "다음 두 글(자아와 기억, Steve Jobs의 유추)이 공통적으로 강조하는 바는?", "",
       ["Connecting new information to what is already familiar or personal makes it easier to accept and understand.",
        "Abstract statistics are the most persuasive form of communication.",
        "New technology should be explained only with entirely new vocabulary.",
        "People remember strangers better than they remember themselves.",
        "Analogy tends to confuse rather than clarify new ideas."], 0,
       "새 정보를 친숙·개인적인 것과 연결할 때 수용·이해가 쉬워진다는 공통 메시지."),
      ("주제", "다음 두 글(대중음악의 민주화, 번역의 집단성)이 공통적으로 부각하는 바는?", "",
       ["What looks like an individual act is in fact shaped by a wider community.",
        "Professional expertise is the only path to good art.",
        "Creativity declines when more people participate.",
        "Tradition must be preserved against any change.",
        "Solitary effort always produces the best results."], 0,
       "개인의 산물처럼 보이는 것(음악·번역)도 실은 더 넓은 공동체가 빚어낸다."),
      ("주제", "다음은 자아와 기억에 관한 글의 요약문이다. 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?",
       "Because the self is the most accessible network, communicators who make abstract information (A)＿＿＿ rather than (B)＿＿＿ are far more effective.",
       ["(A) personal — (B) abstract", "(A) abstract — (B) personal", "(A) statistical — (B) emotional",
        "(A) general — (B) specific", "(A) vivid — (B) personal"], 0,
       "추상을 개인화하는(personal) 쪽이 추상적인(abstract) 쪽보다 효과적이다."),
      ("주제", "다음은 공정한 과정의 역설에 관한 글의 요약문이다. 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?",
       "When a process is fair, we cannot (A)＿＿＿ a bad outcome, so a fair process can paradoxically bring less (B)＿＿＿ than an unfair one.",
       ["(A) externalize — (B) comfort", "(A) internalize — (B) pain", "(A) accept — (B) comfort",
        "(A) externalize — (B) responsibility", "(A) ignore — (B) fairness"], 0,
       "공정하면 결과를 외부화(externalize)할 수 없어 위안(comfort)이 줄어든다."),
      ("주제", "매몰 비용 오류에 관한 글의 제목으로 가장 적절한 것은?", "",
       ["Knowing When to Walk Away", "Never Give Up on Any Investment", "The Joy of Long Relationships",
        "How to Always Win Your Bets", "The Power of Endless Patience"], 0,
       "때로는 손절하고 떠나라는 요지 → 'Knowing When to Walk Away'. ②④⑤는 동기부여처럼 들리지만 본문과 정반대인 함정."),
    ],
  },
  {
    "set_id": "L4-13-5", "level": "L4", "unit": "올림포스 13강 변형",
    "source": "올림포스 13강 변형 5회 (★★★★★ 최고난도·Unit 크로스)",
    "title": "13강 변형 5회 · 추론·Unit 크로스(13↔17·19강) (★★★★★ 킬러)",
    "items": [
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "A vivid, personal message outperforms a dry statistic because it ＿＿＿＿.",
       ["engages the self, the brain's most accessible network", "contains far more numerical data",
        "is much easier to forget over time", "carefully avoids any emotional content",
        "describes total strangers in great detail"], 0,
       "개인적 메시지가 효과적인 이유는 가장 접근이 빠른 네트워크인 자아를 건드리기 때문."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "The sunk cost fallacy persists because giving up forces us to ＿＿＿＿.",
       ["admit that we have wasted something we cannot recover", "gain back all of our original investment",
        "feel proud of our remarkable patience", "avoid any further loss instantly",
        "ignore the cost we have already paid"], 0,
       "포기는 되찾을 수 없는 것을 낭비했다고 인정하도록 강요하므로 매몰비용 오류가 지속된다."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "Jobs's analogies worked because the virtual office was, in essence, ＿＿＿＿ the physical one.",
       ["fundamentally similar to", "completely different from", "far inferior to", "totally unrelated to", "much older than"], 0,
       "가상 사무실은 본질적으로 물리적 사무실과 '근본적으로 유사'했기에 유추가 통했다."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "Reactance arises when our freedom to choose something is ＿＿＿＿.",
       ["taken away", "strengthened", "rewarded", "ignored", "shared"], 0,
       "선택의 자유가 '박탈될' 때 리액턴스가 생긴다(deprive와 연결)."),
      ("어휘", "다음 영영 풀이(English definition)에 해당하는 단어는?",
       "a set of written explanations or notes that help you understand a difficult text",
       ["commentary", "vocabulary", "summary", "biography", "inventory"], 0,
       "'어려운 텍스트 이해를 돕는 설명·주석' = commentary. 5번 지문 Pope 사례의 Greek commentaries."),
      ("어휘", "다음 빈칸에 문맥상 가장 적절한 것은?",
       "We forget an anecdote about a stranger because it makes few ＿＿＿＿ with our existing knowledge.",
       ["associations", "assumptions", "assertions", "assignments", "associates"], 0,
       "기존 지식과의 '연결·연상'(associations). assumption·assertion 등은 형태 유사 함정."),
      ("어법", "다음 글의 밑줄 친 부분 (a)~(e) 중 어법상 틀린 것은?",
       "As outraging as the combination of an unfavorable outcome and an unfair process (a)are, it also (b)brings with it a consolation prize. (c)Believing that the outcome had little to do with us, we reassure ourselves. If the process is fair, we cannot externalize the outcome (d)nearly as easily. The fairer the process, (e)the less comfort we may feel.",
       ["(a)", "(b)", "(c)", "(d)", "(e)"], 0,
       "주어 the combination은 단수 → (a)are가 아니라 is(As … as 양보 도치). 나머지는 적절."),
      ("어법", "다음 글의 밑줄 친 부분 (a)~(e) 중 어법상 틀린 것은?",
       "Suddenly anyone could pick up everyday objects and (a)start a band. This (b)led to genres such as skiffle but also reflected a more relaxed attitude (c)to music making. Groups (d)what had been entirely excluded from music revelled in opportunities (e)to create.",
       ["(a)", "(b)", "(c)", "(d)", "(e)"], 3,
       "선행사 Groups를 받는 관계사가 필요 → (d)what이 아니라 that/who. 나머지는 적절."),
      ("독해", "다음 밑줄 친 부분이 의미하는 바로 가장 적절한 것은?",
       "This is the hidden cost of a fair process.",
       ["Fairness can deprive us of the comfort of blaming external causes.", "A fair process is always financially expensive to run.",
        "Fairness guarantees a better and happier outcome.", "Unfair processes have no real downsides at all.",
        "Hidden fees make fair processes secretly costly."], 0,
       "공정함은 '외부 탓으로 돌리는 위안'을 빼앗는다는 역설이 바로 숨겨진 비용이다."),
      ("독해", "다음 밑줄 친 부분이 의미하는 바로 가장 적절한 것은?",
       "Rather than walk away, we turn a bad five-year relationship into a bad 10-year one.",
       ["Refusing to quit a bad situation only prolongs and deepens it.", "Long relationships are always better than short ones.",
        "Time automatically fixes a bad relationship.", "We should invest even more in failing relationships.",
        "Five years is the ideal length for a relationship."], 0,
       "나쁜 상황을 끝내지 않고 버티면 그것을 더 길고 깊게 만들 뿐이다."),
      ("독해", "다음 글에서 전체 흐름과 관계 없는 문장은?",
       "The self is the brain's largest and most accessible network. ① Information related to us is processed more easily. ② Effective communicators find ways to make the abstract personal. ③ A vivid warning wakes up the self better than a statistic does. ④ The human brain weighs about 1.4 kilograms on average. ⑤ This is why personal framing is so persuasive.",
       ["①", "②", "③", "④", "⑤"], 3,
       "뇌의 무게(④)는 자아·개인화 설득력이라는 흐름과 무관한 문장이다."),
      ("순서", "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
       "Investing in something that hasn't repaid us makes walking away hard. (A) The problem is that staying with a bad bet only increases our loss. (B) Our instinct is to keep investing, hoping it will prove worthwhile. (C) So sometimes we just have to cut our losses.",
       ["(B) — (A) — (C)", "(A) — (B) — (C)", "(B) — (C) — (A)", "(C) — (A) — (B)", "(A) — (C) — (B)"], 0,
       "계속 투자 본능(B) → 하지만 손실만 늘어남(A) → 그래서 손절(C)."),
      ("삽입", "글의 흐름으로 볼 때, 주어진 문장이 들어가기에 가장 적절한 곳은?",
       "〈주어진 문장〉 Ironically, this comes at a price. ── A fair process feels right and just. ( ① ) When the process is fair, we cannot externalize a bad outcome. ( ② ) We are forced to believe the cause lay partly in ourselves. ( ③ ) This is the hidden cost of fairness. ( ④ ) So fairness, for all its virtues, can leave us less comforted. ( ⑤ )",
       ["①", "②", "③", "④", "⑤"], 0,
       "'Ironically, this comes at a price'는 '공정한 과정은 올바르게 느껴진다' 직후의 반전 신호이므로 ①에 들어간다."),
      ("주제", "다음 두 글(공정한 과정의 역설, 매몰 비용 오류)이 공통적으로 보여주는 인간 심리는?", "",
       ["We deal with loss in ways that are emotionally driven, not strictly rational.",
        "We always make decisions that maximize our material gain.",
        "We are completely indifferent to how outcomes are produced.",
        "Fairness and investment never affect our feelings.",
        "We easily let go of bad outcomes and investments."], 0,
       "두 글 모두 손실을 다루는 방식이 이성이 아니라 감정에 좌우됨을 보여준다."),
      ("주제", "다음 두 개념을 종합할 때 가장 적절한 진술은? (Unit 크로스 13↔17강)",
       "〈가〉 희소한 것일수록 더 매력적으로 느껴진다. (13강·리액턴스)  〈나〉 금본위제는 화폐의 발행량을 제한해 그 가치를 뒷받침한다. (17강)",
       ["Limiting the supply of something can increase its perceived value.",
        "Abundant resources are always more valuable than scarce ones.",
        "Value depends only on an object's objective usefulness.",
        "Psychological bias plays no role in economics.",
        "Restricting supply lowers demand for a thing."], 0,
       "〈가〉 희소→매력, 〈나〉 발행량 제한→가치 유지. 공급을 제한하면 인지된 가치가 올라간다는 공통 원리. ⑤는 수요·공급 방향을 뒤집은 함정."),
      ("주제", "다음 두 개념이 공통적으로 시사하는 바는? (Unit 크로스 13↔17강)",
       "〈가〉 대중음악은 접근성을 높여 누구나 창작에 참여할 수 있게 했다. (13강)  〈나〉 양방향 인터넷은 소수의 제작자에게 국한되던 참여를 대중에게 개방했다. (17강)",
       ["New tools can democratize participation that was once limited to a few.",
        "Technology always reduces human creativity.",
        "Only experts ever benefit from new media.",
        "Access to culture has not changed over time.",
        "Centralized control improves participation."], 0,
       "〈가〉 음악 접근성, 〈나〉 양방향 인터넷 모두 소수에게 국한되던 참여를 대중에게 개방한다(민주화)."),
      ("주제", "다음 두 글의 대조가 시사하는 바로 가장 적절한 것은? (Unit 크로스 13↔19강)",
       "〈가〉 신체는 체지방으로 에너지를 효율적으로 저장·관리한다. (19강)  〈나〉 인간은 매몰 비용에 집착해 자원을 비효율적으로 낭비한다. (13강)",
       ["Unlike the body's efficient energy management, human decision-making can cling irrationally to past investments.",
        "The human body and mind both manage their resources perfectly.",
        "Storing body fat is itself an example of the sunk cost fallacy.",
        "Rational calculation governs all human behavior.",
        "Energy and money always follow identical rules."], 0,
       "〈가〉 신체의 효율적 자원 관리 vs 〈나〉 마음의 비효율적 집착의 대조. ③ 체지방 저장을 매몰비용으로 본 것은 오독 함정."),
      ("주제", "다음은 번역의 집단성에 관한 글의 요약문이다. 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?",
       "Although translation may look like a (A)＿＿＿ task, a translator's knowledge and aims are shaped by many other texts and readers, so every translation is really a (B)＿＿＿ one.",
       ["(A) solitary — (B) collective", "(A) collective — (B) solitary", "(A) simple — (B) literal",
        "(A) modern — (B) ancient", "(A) solitary — (B) mechanical"], 0,
       "혼자의 일(solitary)처럼 보이지만 실은 집단적(collective) 행위."),
      ("빈칸", "다음 빈칸에 들어갈 말로 가장 적절한 것은?",
       "Several of these passages suggest that human judgment is often shaped less by objective facts than by ＿＿＿＿.",
       ["psychological framing and bias", "precise mathematical calculation", "pure random chance alone",
        "official rules and laws", "sheer physical strength"], 0,
       "여러 지문(자아·리액턴스·매몰비용·공정 과정)이 공통으로 시사하는 바: 판단은 객관적 사실보다 심리적 프레이밍·편향에 좌우된다."),
      ("주제", "번역의 집단성에 관한 글의 제목으로 가장 적절한 것은?", "",
       ["Every Translation Is a Crowd Translation", "The Lonely Genius of the Translator",
        "Why Machine Translation Always Wins", "The Decline of Classical Languages", "Translating Without Any Sources"], 0,
       "핵심 명제 '모든 번역은 군중 번역' → 'Every Translation Is a Crowd Translation'. ② 고독한 천재는 정반대 함정."),
    ],
  },
]


def build():
    reading = json.load(open(READING, encoding="utf-8"))
    bank = json.load(open(BANK, encoding="utf-8"))

    new_sets, new_drill = [], []
    for s in SETS:
        tag = "-".join(s["set_id"].split("-")[1:])   # L1-13-1 → 13-1
        qs = []
        for n, (t, stem, lead, opts, ans, exp) in enumerate(s["items"], 1):
            assert 0 <= ans < len(opts), f"{s['set_id']} #{n} 정답 범위 오류"
            qs.append({"id": f"V{n}", "passage": 0, "type": t, "stem": stem,
                       "lead": lead, "options": opts, "answer": ans, "explain": exp})
            new_drill.append({"id": f"var-{tag}-{n}", "track": "drill", "group": GROUP[t],
                              "unit": s["unit"], "type": "mc", "source": s["source"],
                              "passage": lead, "stem": stem, "options": opts,
                              "answer": ans, "explain": exp})
        new_sets.append({"id": s["set_id"], "level": s["level"], "source": s["source"],
                         "title": s["title"], "passages": [], "questions": qs})

    # reading: L0 유지, L1~L4 변형 세트 교체
    reading["sets"] = [x for x in reading["sets"] if x["id"].split("-")[0] == "L0"] + new_sets
    # bank: var-* 교체
    bank["items"] = [i for i in bank["items"] if not str(i.get("id", "")).startswith("var-")] + new_drill

    json.dump(reading, open(READING, "w", encoding="utf-8"), ensure_ascii=False, separators=(",", ":"))
    json.dump(bank, open(BANK, "w", encoding="utf-8"), ensure_ascii=False, separators=(",", ":"))

    print("변형 세트:", [s["id"] for s in new_sets])
    print("레벨 분포:", dict(Counter(s["level"] for s in new_sets)))
    print("drill var 항목:", len(new_drill), "| 유형:", dict(Counter(d["group"] for d in new_drill)))
    print("reading sets 총:", len(reading["sets"]), "| bank items 총:", len(bank["items"]))


if __name__ == "__main__":
    build()
