# -*- coding: utf-8 -*-
"""
변형 회차가 참조하는 '올림포스 N강 시험범위 원문' 지문 (영어+한글).
출처: 노션 "올림포스 N강 시험범위 원문" 페이지. build_variants.py가 import해서
 - reading 변형 세트의 passages를 채우고(강 전체 지문)
 - bank 지문필수 var-* 문항에 해당 지문(passage)을 부착한다.

키: 강("13","15","17","19","E"=엘리트) → 지문번호(int) → {title, source, en, ko}
"""

PASSAGES = {
  "13": {
    1: {
      "title": "자아와 기억",
      "source": "2025년 6월 고2 학평 31번",
      "en": "We might forget an anecdote about a stranger because it makes few connections with our existing associations, but we won't forget a piece of gossip about our cousin. There's one complex network that is larger and quicker to access than all others ─ the self. We've been thinking about ourselves in our whole lives. So if a new piece of information has something to do with us, it will be more easily and thoroughly processed. It hits even closer to home than our actual home ─ we can take a vacation away from our home, but not from ourselves. The most effective communicators find ways to make the abstract personal. Consider the warning that law schools give to motivate first-year law students concerning the rigors of their program. Hearing that \"the first-year dropout rate is 33%\" is an abstract statistic. \"Look to your left, look to your right. One of the three of you won't be joining us next fall\" wakes up the self.",
      "ko": "우리는 우리의 기존 연상들과 연관성이 거의 없기 때문에 낯선 사람에 관한 일화는 잊어버릴지 모르지만, 우리의 사촌에 관한 소문은 한 부분도 잊지 않을 것이다. 다른 모든 것보다 더 크고 접근하기에 더 빠른 하나의 복잡한 네트워크, 바로 자아이다. 우리는 평생 우리 자신에 대해 생각해 왔다. 그래서 어떤 새로운 정보가 '우리'와 관련이 있다면, 그것은 더 쉽게 그리고 더 철저하게 처리될 것이다. 그것은 우리의 실제 집보다 훨씬 더 가깝게 와닿는다. 우리는 집으로부터 떠나 휴가를 갈 수 있지만, '우리 자신'으로부터는 아니다. 가장 효과적인 의사소통자들은 추상적인 것을 개인적인 것으로 만드는 방법을 찾는다. 로스쿨이 그들의 프로그램의 엄격함에 대해 1학년 로스쿨 학생들에게 동기를 부여하기 위해 주는 경고를 생각해 보라. \"첫해 중도 탈락률은 33%입니다\"라고 듣는 것은 추상적인 통계이다. \"여러분의 왼쪽을 보세요, 여러분의 오른쪽을 보세요. 여러분 세 명 중 한 명은 내년 가을에 우리와 함께하지 않을 것입니다\"는 자아를 일깨운다.",
    },
    2: {
      "title": "Steve Jobs의 유추",
      "source": "2025년 6월 고2 학평 32번",
      "en": "Steve Jobs used analogy to get people to embrace the new technology. Before computers, people worked in a physical world. We used paper and pens and physical file folders and so on. The idea of working in a virtual world was radically different. Or at least seemed radically different. What Jobs understood was that a physical office was fundamentally similar to a virtual office. To win over the masses, Jobs drew strong analogies between the traditional workplace people knew well with the new, unfamiliar virtual workplace. In the pre-computer workplace, when ideas were written on paper it was called ... a document. When those documents needed to be stored they were put in ... a folder. And those folders were kept on ... a desk. Documents, folders, and desktops are the terms we use in our virtual work because Steve Jobs understood that using familiar terms would make the new technology easier to understand. The parallels between the physical and virtual workplace now seem obvious.",
      "ko": "Steve Jobs는 사람들이 새로운 기술을 받아들이도록 하기 위해 유사성을 사용했다. 컴퓨터 이전에, 사람들은 물리적인 세계에서 일을 했다. 우리는 종이와 펜과 물리적인 파일 폴더 등을 사용했다. 가상 세계에서 일한다는 개념은 혁신적으로 달랐다. 혹은 적어도 근본적으로 다르게 '보였다'. Jobs가 이해한 것은 물리적인 사무실이 근본적으로 가상 사무실과 유사하다는 것이었다. 대중을 사로잡기 위해, Jobs는 사람들이 잘 알고 있는 전통적인 일터와 새롭고, 낯선 가상 일터 간의 강한 유사성을 끌어냈다. 컴퓨터 이전의 일터에서, 생각이 종이에 쓰이면 그것은 ... 문서(document)라고 불렸다. 그 문서들이 저장될 필요가 있을 때 그것들은 ... 폴더(folder)에 넣어졌다. 그리고 그 폴더들은 ... 책상(desk)에 보관되었다. 문서, 폴더, 그리고 데스크톱은 Steve Jobs가 친숙한 용어를 사용하는 것이 새로운 기술을 이해하기 더 쉽게 만들리라는 것을 이해했기 때문에 우리가 우리의 가상 작업에서 사용하는 용어들이다. 물리적 일터와 가상 일터 사이의 유사점이 지금은 분명해 보인다.",
    },
    3: {
      "title": "대중음악과 접근성",
      "source": "2025년 3월 고2 학평 31번",
      "en": "The explosion of popular music in the second half of the twentieth century as well as the global circulation and dissemination of music by the creative industries propelled a new understanding of accessibility in relation to music. Suddenly, in the 1950s, anyone could pick up spoons, a couple of pans, a second-hand guitar and start a band. This led to specific genres such as skiffle, but also, more generally, reflected a much more relaxed and inclusive attitude to music making. While ordinary people had always sung and made music, the popular music movement was driven by a spirit of rebellion and freedom. This approach led to the punk movement, whose musicians even made it a condition for their music to be non-virtuosic and accessible to all in the 1970s. Groups who had been entirely excluded from music revelled in opportunities to create. This led to a sense of novelty and empowerment in and beyond the music sphere.",
      "ko": "창작 산업계의 전 세계적 음악 유통과 보급뿐만 아니라 20세기 후반의 대중음악의 폭발적 증가는 음악과 관련된 접근성에 대한 새로운 이해를 촉진했다. 갑자기, 1950년대에, 누구나 숟가락, 냄비 몇 개, 중고 기타를 집어 들고 밴드를 시작할 수 있었다. 이는 스키플(skiffle)과 같은 특정 장르로 이어졌을 뿐만 아니라, 또한, 더 일반적으로는, 음악 제작에 대한 훨씬 더 여유롭고 포용적인 태도를 반영했다. 평범한 사람들이 항상 노래를 부르고 음악을 만들어 왔었지만, 대중음악 운동은 저항과 자유 정신에 의해 촉진되었다. 이러한 접근 방식은 펑크 운동으로 이어졌으며, 이 운동의 음악가들은 1970년대에 심지어 자신의 음악이 전문성이 높지 않고 모든 사람에게 접근 가능해야 한다는 조건을 내걸었다. 음악에서 완전히 배제되었던 사람들은 창작할 수 있는 기회를 만끽했다. 이는 음악계 안팎에서 참신성과 자율성이라는 인식으로 이어졌다.",
    },
    5: {
      "title": "모든 번역은 군중 번역이다",
      "source": "2024년 10월 고2 학평 32번",
      "en": "All translators feel some pressure from the community of readers for whom they are doing their work. And all translators arrive at their interpretations in dialogue with other people. The English poet Alexander Pope had pretty good Greek, but when he set about translating Homer's Iliad in the early 18th century he was not on his own. He had Greek commentaries to refer to, and translations that had already been done in English, Latin, and French ─ and of course he had dictionaries. Translators always draw on more than one source text. Even when the scene of translation consists of just one person with a pen, paper, and the book that is being translated, or even when it is just one person translating orally for another, that person's linguistic knowledge arises from lots of other texts and other conversations. And then his or her idea of the translation's purpose will be influenced by the expectations of the person or people it is for. In both these senses every translation is a crowd translation.",
      "ko": "모든 번역가들은 그들이 대상으로 작업하고 있는 독자들의 공동체로부터 약간의 압박을 느낀다. 그리고 모든 번역가들은 다른 사람들과의 대화에서 그들의 해석에 도달한다. 영국의 시인 알렉산더 포프는 그리스어를 꽤 잘했지만, 18세기 초에 호머의 'Iliad'를 번역하기 시작했을 때 그는 혼자 한 것이 아니었다. 그는 참고할 그리스어 해설과 이미 영어, 라틴어, 프랑스어로 된 번역본을 가지고 있었고, 물론 사전도 가지고 있었다. 번역가들은 항상 한 가지 이상의 원문을 활용한다. 심지어 번역 현장이 하나의 펜, 종이, 그리고 번역 중인 책을 가진 단 한 사람으로 구성되어 있을 때나, 한 사람이 다른 사람을 위해 구두로 번역 중일 때에도, 그 사람의 언어적 지식은 많은 다른 텍스트와 다른 대화에서 발생한다. 그러고 나서 번역의 목적에 대한 그 또는 그녀의 생각은 이것의 대상이 되는 사람 또는 사람들의 기대에 의해 영향을 받는다. 이 두 가지 의미에서 모든 번역은 군중 번역이다.",
    },
    6: {
      "title": "공정한 과정의 역설",
      "source": "2024년 9월 고2 학평 31번",
      "en": "When we receive an unfavorable outcome, in some ways the very last thing we want to hear is that the process was fair. As outraging as the combination of an unfavorable outcome and an unfair process is, this combination also brings with it a consolation prize: the possibility of attributing the bad outcome to something other than ourselves. We may reassure ourselves by believing that our bad outcome had little to do with us and everything to do with the unfair process. If the process is fair, however, we cannot nearly as easily externalize the outcome; we got what we got \"fair and square.\" When the process is fair we believe that our outcome is deserved, which is another way of saying that there must have been something about ourselves (what we did or who we are) that caused the outcome.",
      "ko": "우리가 불리한 결과를 얻을 때, 어떤 면에서 우리가 '가장 듣고 싶지 않은' 말은 그 과정이 공정했다는 말이다. 불리한 결과와 불공정한 과정의 결합이 분노를 일으키지만, 이 결합은 또한 위로의 상, 즉 나쁜 결과를 우리 자신 이외의 다른 무언가의 탓으로 돌릴 가능성을 더불어 가져다준다. 우리는 우리의 나쁜 결과가 우리와는 거의 관련이 없었고 불공정한 과정과 전적으로 관련이 있었다고 믿음으로써 우리 자신을 안심시킬지도 모른다. 하지만 그 과정이 공정하다면, 우리는 결과를 그만큼 쉽게 외부화할 수 없으며, 우리는 우리가 얻은 것을 '정정당당하게' 얻은 것이다. 그 과정이 공정할 때 우리는 우리의 결과가 마땅하다고 믿게 되는데, 이는 그 결과를 초래한 우리 자신(우리가 무엇을 했는지 또는 우리가 누구인지)에 관한 무언가가 틀림없이 있었을 것이라고 말하는 또 다른 방식이다.",
    },
    7: {
      "title": "희소성과 리액턴스",
      "source": "2024년 6월 고2 학평 31번",
      "en": "We collect stamps, coins, vintage cars even when they serve no practical purpose. The post office doesn't accept the old stamps, the banks don't take old coins, and the vintage cars are no longer allowed on the road. These are all side issues; the attraction is that they are in short supply. In one study, students were asked to arrange ten posters in order of attractiveness ─ with the agreement that afterward they could keep one poster as a reward for their participation. Five minutes later, they were told that the poster with the third highest rating was no longer available. Then they were asked to judge all ten from scratch. The poster that was no longer available was suddenly classified as the most beautiful. In psychology, this phenomenon is called reactance: when we are deprived of an option, we suddenly deem it more attractive.",
      "ko": "우리는 그것들이 실용적인 목적을 수행하지 않더라도 우표, 동전, 빈티지 자동차들을 수집한다. 우체국은 오래된 우표를 받지 않고, 은행은 오래된 동전을 받지 않으며, 그리고 빈티지 자동차는 더 이상 도로에서 허용되지 않는다. 이런 것들은 모두 부수적인 문제이다. 매력은 그것들이 부족한 공급에 있다는 것이다. 한 연구에서, 학생들은 나중에 그들의 참여에 대한 보상으로 포스터 1장을 간직할 수 있다는 합의와 함께 포스터 10장을 매력도의 순서대로 배열하도록 요청받았다. 5분 후, 그들은 세 번째 높은 평가의 포스터가 더 이상 이용할 수 없다는 것을 들었다. 그런 다음 그들은 10개의 포스터를 모두 맨 처음부터 평가하라는 요청을 받았다. 더 이상 이용할 수 없는 포스터가 갑자기 가장 아름다운 것으로 분류되었다. 심리학에서, 이러한 현상은 '리액턴스'라고 불린다. 우리가 선택지를 빼앗겼을 때, 우리는 그것을 갑자기 더 매력적으로 여긴다.",
    },
    8: {
      "title": "매몰 비용 오류",
      "source": "2024년 6월 고2 학평 32번",
      "en": "If we've invested in something that hasn't repaid us ─ be it money in a failing venture, or time in an unhappy relationship ─ we find it very difficult to walk away. This is the sunk cost fallacy. Our instinct is to continue investing money or time as we hope that our investment will prove to be worthwhile in the end. Giving up would mean acknowledging that we've wasted something we can't get back, and that thought is so painful that we prefer to avoid it if we can. The problem, of course, is that if something really is a bad bet, then staying with it simply increases the amount we lose. Rather than walk away from a bad five-year relationship, for example, we turn it into a bad 10-year relationship; rather than accept that we've lost a thousand dollars, we lay down another thousand and lose that too. In the end, by delaying the pain of admitting our problem, we only add to it. Sometimes we just have to cut our losses.",
      "ko": "우리에게 보답해 주지 않는 무언가에 우리가 투자해 왔다면, 실패한 사업에 투자한 돈이거나, 불행한 인간관계에 투자한 시간이던지 간에 우리는 벗어나기가 매우 어렵다는 것을 안다. 이것은 매몰 비용 오류이다. 우리의 본능은 결국에는 우리의 투자가 가치 있는 것으로 입증될 것이라고 희망하면서 돈이나 시간에 투자를 계속하는 것이다. 포기한다는 것은 우리가 돌이킬 수 없는 무언가를 낭비해 왔다고 인정하는 것을 의미하고, 그런 생각은 너무 고통스러워서 우리가 할 수 있다면 그것을 피하기를 선호한다. 물론, 문제는 어떤 것이 정말 나쁜 투자라면, 그것을 계속하는 것은 우리가 잃는 총액을 증가시킬 뿐이라는 것이다. 예를 들어, 5년의 나쁜 관계에서 벗어나기보다는 우리는 그것을 10년의 나쁜 관계로 바꾸고, 천 달러를 잃었다는 사실을 받아들이기보다는 또 다른 천 달러를 내놓고 그것도 역시 잃는다. 결국, 우리의 문제를 인정하는 고통을 미룸으로써 우리는 그것(고통)을 키울 뿐이다. 때때로 우리는 손실을 끊어야만 한다.",
    },
  },
  "15": {
    1: {
      "title": "상대성 이론과 중력 렌즈",
      "source": "2025년 9월 고2 학평 35번",
      "en": "According to Einstein's theory, a large mass like the Sun 'bends' space-time. Newton's theory makes no such prediction. This bending of space-time leads to phenomena such as 'gravitational lensing' where the light of distant stars appears to be in different locations when they pass by a large mass like the Sun. We don't normally see this lensing because stars aren't visible during the day when the Sun is out, but a solar eclipse in 1919 allowed scientists to observe what the Sun's gravity was doing to the light from distant stars. The stars around the Sun appeared to have moved from their normal positions in the night sky. The shift was much larger than Newton's theory predicted, but exactly in the positions predicted by Einstein's theory.",
      "ko": "아인슈타인의 이론에 따르면, 태양과 같은 큰 질량은 시공간을 '휘어지게 한다'. 뉴턴의 이론은 그런 예측을 하지 않는다. 이런 시공간의 휘어짐은 멀리 있는 별의 빛이 태양과 같은 거대한 질량 옆을 지날 때 다른 위치에 있는 것처럼 보이는 '중력 렌즈 효과'와 같은 현상으로 이어진다. 우리는 태양이 떠 있는 낮에는 별들이 보이지 않기 때문에 이러한 렌즈 효과를 보통 보지 못하지만, 1919년의 일식은 태양의 중력이 멀리 있는 별로부터 오는 빛에 어떤 영향을 주는지 과학자들이 관찰할 수 있게 해 주었다. 태양 주변의 별들은 밤하늘의 그것들의 정상적인 위치에서부터 이동한 것처럼 보였다. 그 이동은 뉴턴의 이론이 예측한 것보다 훨씬 더 컸지만, 아인슈타인의 이론에 의해 예측된 위치에 정확히 있었다.",
    },
    2: {
      "title": "발과 다리의 정직함",
      "source": "2025년 6월 고2 학평 35번",
      "en": "The writer and zoologist Desmond Morris observed that our feet communicate exactly what we think and feel more honestly than any other part of our bodies. Why are the feet and legs such accurate reflectors of our sentiments? For millions of years, long before humans spoke, our legs and feet reacted to environmental threats (e.g., hot sand, ill-tempered lions) instantaneously, without the need for conscious thought. Our limbic brains made sure that our feet and legs reacted as needed by either ceasing motion, running away, or kicking at a potential threat. This survival regimen, retained from our ancestral heritage, has served us well and continues to do so today. In fact, these age-old reactions are still so hardwired in us that when we are presented with something dangerous or even disagreeable, our feet and legs still react as they did in prehistoric times.",
      "ko": "작가이자 동물학자인 Desmond Morris는 우리의 발이 우리가 생각하는 것을 정확하게 전달하고 우리 몸의 다른 어떤 부위보다 더 정직하게 느낀다는 것을 관찰했다. 왜 발과 다리는 우리 감정을 그토록 정확하게 비추는 반사경일까? 수백만 년 동안, 인간이 말을 하기 훨씬 이전에, 우리의 다리와 발은 환경적인 위협(예를 들면, 뜨거운 모래, 성질이 나쁜 사자)에 대해 의식적 사고에 대한 필요 없이, 즉시 반응했다. 우리의 변연계 뇌는 움직임을 멈추거나 도망가거나 혹은 잠재적인 위협에 저항함으로써 필요에 따라 우리의 발과 다리가 반드시 반응하도록 했다. 우리 조상의 유산으로부터 유지되어 온 이러한 생존 양생법은, 우리에게 도움이 되어 왔고 오늘날에도 계속 그러하다. 사실, 이러한 오래된 반응은 여전히 우리 안에 깊이 각인되어 있어서 우리가 위험하거나 심지어 불쾌한 것에 직면할 때, 우리의 발과 다리는 선사 시대에 그랬던 것처럼 여전히 반응한다.",
    },
    4: {
      "title": "최소 가공의 중요성",
      "source": "2024년 9월 고2 학평 35번",
      "en": "Minimal processing can be one of the best ways to keep original flavors and taste, without any need to add artificial flavoring or additives, or too much salt. This would also be the efficient way to keep most nutrients, especially the most sensitive ones such as many vitamins and anti-oxidants. Milling of cereals is one of the most harsh processes which dramatically affect nutrient content. While grains are naturally very rich in micronutrients, anti-oxidants and fiber (i.e. in wholemeal flour or flakes), milling usually removes the vast majority of minerals, vitamins and fibers to raise white flour. Such a spoilage of key nutrients and fiber is no longer acceptable in the context of a sustainable diet aiming at an optimal nutrient density and health protection. In contrast, fermentation of various foodstuffs or germination of grains are traditional, locally accessible, low-energy and highly nutritious processes of sounded interest.",
      "ko": "최소한의 가공은 인공 향료나 첨가물, 또는 과도한 소금을 넣을 필요 없이 본연의 풍미와 맛을 유지하는 가장 좋은 방법 중 하나일 수 있다. 이것은 또한 대부분의 영양소, 특히 많은 비타민과 항산화 물질과 같은 가장 민감한 영양소를 유지하는 효율적인 방법일 수 있다. 곡물을 제분하는 것은 영양소 함량에 크게 영향을 미치는 가장 가혹한 과정 중 하나이다. 곡물에는 (즉 통밀 가루 또는 플레이크에는) 미량의 영양소, 항산화 물질, 그리고 섬유질이 자연적으로 매우 풍부하지만, 제분이 일반적으로 흰 밀가루를 만들기 위해 대부분의 미네랄, 비타민 그리고 섬유질을 제거한다. 주요 영양소와 섬유질의 그러한 손상은 최적의 영양소 밀도와 건강 보호를 목표로 하는 지속 가능한 식단의 맥락에서 더 이상 받아들여질 수 없다. 대조적으로, 다양한 식품의 발효나 곡물의 발아는 알려진 관심을 받는 전통적이고, 현지에서 접근 가능하며, 에너지가 적게 들고, 매우 영양가 있는 과정이다.",
    },
    5: {
      "title": "데이터보다 해석의 가치",
      "source": "2024년 6월 고2 학평 35번",
      "en": "As the old joke goes: \"Software, free. User manual, $10,000.\" But it's no joke. A couple of high-profile companies make their living selling instruction and paid support for free software. The copy of code, being mere bits, is free. The lines of free code become valuable to you only through support and guidance. A lot of medical and genetic information will go this route in the coming decades. Right now getting a full copy of all your DNA is very expensive ($10,000), but soon it won't be. The price is dropping so fast, it will be $100 soon, and then the next year insurance companies will offer to sequence you for free. When a copy of your sequence costs nothing, the interpretation of what it means, what you can do about it, and how to use it ─ the manual for your genes ─ will be expensive.",
      "ko": "옛 농담에 따르면 '소프트웨어, 무료. 사용자 설명서, 10,000달러'라는 말이 있다. 하지만 그것은 농담이 아니다. 세간의 이목을 끄는 몇몇 기업들은 무료 소프트웨어에 대한 지침과 유료 지원을 판매하면서 돈을 번다. 단지 몇 비트일 뿐인 코드 사본은 무료이다. 무료 코드의 배열은 지원과 안내를 통해서만 여러분에게 가치 있게 된다. 다가올 수십 년 안에 많은 의료 및 유전 정보가 이 경로를 따르게 될 것이다. 지금은 여러분의 모든 DNA의 전체 사본을 얻는 것이 매우 비싸지만 (10,000달러), 곧 그렇지 않게 될 것이다. 가격이 너무 빨리 떨어지고 있어, 곧 100달러가 될 것이고, 그다음 해에는 보험 회사가 무료로 여러분의 유전자 배열 순서를 밝혀 줄 것을 제안할 것이다. 여러분의 배열 사본에 비용이 들지 않을 때, 그것이 의미하는 것, 여러분이 그것에 관해 할 수 있는 것, 그리고 그것을 사용하는 방법에 관한 설명, 즉 여러분의 유전자 설명서는 비싸질 것이다.",
    },
    6: {
      "title": "향신료와 생존 전략",
      "source": "2024년 3월 고2 학평 35번",
      "en": "We are the only species that seasons its food, deliberately altering it with the highly flavored plant parts we call herbs and spices. It's quite possible that our taste for spices has an evolutionary root. Many spices have antibacterial properties ─ in fact, common seasonings such as garlic, onion, and oregano inhibit the growth of almost every bacterium tested. And the cultures that make the heaviest use of spices ─ think of the garlic and black pepper of Thai food, the ginger and coriander of India, the chili peppers of Mexico ─ come from warmer climates, where bacterial spoilage is a bigger issue. In contrast, the most lightly spiced cuisines ─ those of Scandinavia and northern Europe ─ are from cooler climates. Our uniquely human attention to flavor, in this case the flavor of spices, turns out to have arisen as a matter of life and death.",
      "ko": "우리는 음식에 양념을 하는 유일한 종으로, 허브와 향신료라고 부르는 강한 맛을 내는 식물의 부분을 이용하여 그것(음식)을 의도적으로 바꾼다. 향신료에 대한 우리의 미각은 진화적 뿌리를 가지고 있을 가능성이 꽤 있다. 많은 향신료가 항균성을 가지고 있는데, 실제로 마늘, 양파, 오레가노와 같은 흔한 조미료들이 거의 모든 확인된 박테리아의 성장을 억제한다. 그리고 태국 음식의 마늘과 후추, 인도의 생강과 고수, 멕시코의 고추를 생각해 보면, 향신료를 가장 많이 사용하는 문화권은 더 따뜻한 기후에서 유래하는데, 그곳에서는 박테리아에 의한 (음식의) 부패가 더 큰 문제이다. 반대로, 스칸디나비아와 북유럽의 요리같이 향신료를 가장 적게 쓰는 요리는 더 서늘한 기후에서 유래한다. 맛에 대한 인간 특유의 관심, 이 경우 향신료의 맛이, 생사의 문제로서 생겨난 것으로 드러난다.",
    },
  },
  "17": {
    1: {
      "title": "이주의 긍정적 효과",
      "source": "2025년 6월 고2 학평 38번",
      "en": "The word \"migration\" is almost always reported in the popular media and even in scientific literature as a problem or a crisis. For example, migrants are assumed to overcrowd cities, clog up labor markets, and increase poverty. The other questionable assumption is that most migration is involuntary ─ people fleeing natural or man-made disasters. The reality, however, is more complex, and many migrants are simply seeking greater economic opportunity. Of course migration can and does create social and economic problems. But migration can also be a solution for many preexisting problems. For example, out-migration generally redistributes workers from places of labor surplus to areas where there is greater demand or more opportunity. Migration is generally selective of persons who are younger, healthier, more flexible, and more willing to endure hardship in hopes of a better life relative to their prospects in their places of origin. Most research that examines long-term outcomes of migration, including remittances and intergenerational mobility, finds positive \"long-term\" effects on places of origin and destination.",
      "ko": "'이주'라는 단어는 대중 매체와 심지어 과학 문헌에서도 문제나 위기로 거의 항상 보도된다. 예를 들어, 이주민들이 도시를 과밀화시키고, 노동 시장을 막히게 하며, 빈곤을 증가시킨다고 가정된다. 또 다른 의문스러운 가정은 대부분의 이주가 비자발적이라는 것이다. 즉, 자연적 또는 인위적인 재난을 피해 떠나는 사람들이라는 것이다. 그러나 현실은 더 복잡하고, 많은 이주민들은 단순히 더 큰 경제적 기회를 찾고 있다. 물론 이주는 사회적, 경제적 문제를 일으킬 수 있고 정말로 일으킨다. 하지만 이주는 또한 많은 기존의 문제에 대한 해결책이 될 수 있다. 예를 들어, 외부 이주는 일반적으로 노동 과잉 지역에서 더 큰 수요나 더 많은 기회가 있는 지역으로 노동자를 재분배한다. 이주는 더 젊고, 더 건강하고, 더 유연하며, 그들의 본거지에서의 그들의 전망에 비해 더 나은 삶을 희망하며 고난을 더 기꺼이 견딜 사람들을 일반적으로 선택한다. 이주의 장기적인 결과를 조사하는 대부분의 연구는, 송금과 세대 간 이동을 포함하여, 본거지와 목적지에서 긍정적인 '장기적' 효과를 발견한다.",
    },
    2: {
      "title": "금본위제의 이유",
      "source": "2025년 6월 고2 학평 39번",
      "en": "The big problem with money made by governments is that those who run the government are always faced with the temptation to make more of it and spend it. Whether among ancient kings or modern politicians, this has happened again and again over the centuries, leading to inflation and the many economic and social problems that follow from inflation. For this reason, many countries have preferred using gold, silver, or some other material that is inherently limited in supply, as money. It is a way of depriving governments of the power to expand the money supply to inflationary levels. Gold has long been considered ideal for this purpose, since the supply of gold in the world usually cannot be increased rapidly. When paper money is convertible into gold whenever the individual chooses to do so, then the money is said to be \"backed up\" by gold. This expression is misleading only if we imagine that the value of the gold is somehow transferred to the paper money, when in fact the real point is that the gold simply limits the amount of paper money that can be issued.",
      "ko": "정부에 의해 만들어지는 돈에 대한 큰 문제는 정부를 운영하는 사람들이 더 많은 돈을 만들고 그것을 쓰고 싶은 유혹에 항상 직면한다는 것이다. 고대 왕들 중에서나 현대 정치인들 중에서든, 이것은 수 세기 동안 반복되어 일어났으며, 그로 인해 인플레이션과 인플레이션에서 비롯되는 많은 경제적, 사회적 문제들을 초래했다. 이러한 이유로, 많은 국가들은 금, 은, 또는 본질적으로 공급이 제한된 어떤 다른 물질을 돈으로 사용하는 것을 선호해 왔다. 그것은 정부에게서 돈 공급을 인플레이션 수준으로 확장할 수 있는 권한을 박탈하는 방법이다. 금은 오랫동안 이 목적에 이상적인 것으로 여겨져 왔는데, 전 세계의 금 공급이 보통 급격히 증가될 수 없기 때문이다. 개인이 그렇게 하기를 선택할 때마다 종이돈이 금으로 전환될 수 있을 때, 그러면 그 돈은 금에 의해 '보장된다'라고 말해진다. 이 표현은 우리가 금의 가치가 어떤 방식으로든 종이돈으로 전환된다고 생각하는 경우에만 오해를 살 수 있는데, 이때 사실상 진짜 요점은 금은 발행될 수 있는 종이돈의 양을 단순히 제한한다는 것이다.",
    },
    4: {
      "title": "홉스의 자연 상태와 국가",
      "source": "2024년 10월 고2 학평 39번",
      "en": "According to Hobbes, man is not a being who can act morally in spite of his instinct to protect his existence in the state of nature. Hence, the only place where morality and moral liberty will begin to find an application begins in a place where a sovereign power, namely the state, emerges. Hobbes thus describes the state of nature as a circumstance in which man's life is \"solitary, poor, nasty, brutish and short\". It means when people live without a general power to control them all, they are indeed in a state of war. In other words, Hobbes, who accepted that human beings are not social and political beings in the state of nature, believes that without the power human beings in the state of nature are \"antisocial and rational based on their selfishness\". Moreover, since society is not a natural phenomenon and there is no natural force bringing people together, what will bring them together as a society is not mutual affection according to Hobbes. It is, rather, mutual fear of men's present and future that assembles them, since the cause of fear is a common drive among people in the state of nature.",
      "ko": "홉스에 따르면, 인간은 자연 상태에서 자신의 존재를 보호하려는 그의 본능을 무릅쓰고 도덕적으로 행동할 수 있는 존재가 아니다. 따라서 도덕과 도덕적 자유가 적용을 찾기 시작하는 유일한 곳은 군림하는 권력, 즉 국가가 출현하는 곳에서 시작한다. 따라서 홉스는 자연 상태를 인간의 삶이 '고독하고, 가난하며, 불결하고, 잔인하고, 짧은' 상황으로 묘사한다. 그것은 사람들이 그들 모두를 통제할 일반적인 권력 없이 살아갈 때, 그들은 실로 전쟁 상태에 놓여 있는 것임을 의미한다. 다시 말해, 자연 상태에 있는 인간은 사회적이고 정치적인 존재가 아니라는 것을 인정한 홉스는 그 권력이 없이 자연 상태에 있는 인간은 '이기심에 기초해 반사회적이고 이성적'이라고 믿는다. 게다가, 사회는 자연적인 현상이 아니며 사람들을 하나로 모으는 자연적인 힘도 없기 때문에, 홉스에 따르면 그들을 사회로 함께 모이게 하는 것은 상호 간의 애정이 아니다. 두려움의 원인이 자연 상태에 있는 사람들 사이의 공통된 추진력이기 때문에, 오히려, 그들을 모으는 것은 인간의 현재와 미래에 대한 상호 간의 두려움이다.",
    },
    5: {
      "title": "동면과 수면의 차이",
      "source": "2024년 9월 고2 학평 39번",
      "en": "Sleep is clearly more than just resting. One curious fact is that animals that are hibernating also have periods of sleep. It comes as a surprise to most of us, but hibernation and sleep are not the same thing at all, at least not from a neurological and metabolic perspective. Hibernating is more like being anesthetized: the subject is unconscious but not actually asleep. So a hibernating animal needs to get a few hours of conventional sleep each day within the larger unconsciousness. A further surprise to most of us is that bears, the most famous of wintry sleepers, don't actually hibernate. Real hibernation involves profound unconsciousness and a dramatic fall in body temperature ─ often to around 32 degrees Fahrenheit. By this definition, bears don't hibernate, because their body temperature stays near normal and they are easily awakened. Their winter sleeps are more accurately called a state of torpor.",
      "ko": "잠은 분명 단지 휴식하는 것 이상이다. 한 가지 호기심을 끄는 사실은 동면하고 있는 동물들 또한 잠자는 기간을 가진다는 점이다. 그것은 우리 대부분에게 놀라움으로 다가오지만, 동면과 수면은 적어도 신경학적이고 신진대사적인 관점에서 볼 때 전혀 같은 것이 아니다. 동면은 마취되는 것과 더욱 비슷한데, 그 대상은 의식이 없지만 실제로 잠들어 있지는 않다. 그래서 동면하고 있는 동물은 더 큰 무의식 속에서 매일 몇 시간의 전형적인 잠을 잘 필요가 있다. 우리 대부분에게 더욱 놀라운 점은 겨울에 잠을 자는 동물 중 가장 유명한 곰도 실제로는 동면하지 않는다는 것이다. 실제 동면은 깊은 무의식과 체온의 급격한 하락을 포함하는데, 자주 대략 화씨 32도로 떨어진다. 이러한 정의에 따르면, 곰의 체온은 정상 근처를 유지하고 쉽게 잠에서 깨어나기 때문에 그것들은 동면하지 않는다. 그것들의 겨울잠은 더 정확하게는 휴면 상태라고 불린다.",
    },
    6: {
      "title": "양방향성의 인터넷",
      "source": "2024년 6월 고2 학평 38번",
      "en": "The Internet differs from most of the mass media it replaces in an obvious and very important way: it works in two directions. We can send messages through the network as well as receive them, which has made the system all the more useful. The ability to exchange information online, to upload as well as download, has turned the Net into a thoroughfare for business and commerce. With a few clicks, people can search virtual catalogues, place orders, track shipments, and update information in corporate databases. But the Net doesn't just connect us with businesses; it connects us with one another. It's a personal broadcasting medium as well as a commercial one. Millions of people use it to distribute their own digital creations, in the form of blogs, videos, photos, songs, and podcasts, as well as to critique, edit, or otherwise modify the creations of others.",
      "ko": "인터넷은 그것이 대체하는 대부분의 대중 매체와 분명하고도 매우 중요한 방식으로 다르다. 그것은 두 방향으로 작용한다. 우리는 네트워크를 통해 메시지들을 받을 수 있을 뿐만 아니라 그것들을 보낼 수도 있는데, 이것은 그 시스템을 훨씬 더 유용하게 만들었다. 온라인에서 정보를 교환하고, 다운로드할 뿐만 아니라 업로드하는 능력은, 인터넷을 비즈니스와 상거래를 위한 통로로 만들었다. 몇 번의 클릭으로, 사람들은 가상 카탈로그를 검색하고, 주문을 하고, 배송을 추적하고, 그리고 기업의 데이터베이스에 정보를 업데이트할 수 있다. 하지만 인터넷은 단지 우리를 기업과 연결하는 것만은 아니다. 그것은 우리를 서로서로 연결한다. 그것은 상업용 매체일 뿐만 아니라 개인 방송 매체이다. 수백만 명의 사람들이 다른 사람들의 창작물을 비평하고, 편집하고, 또는 그렇지 않으면 수정하기 위해서뿐만 아니라, 블로그, 동영상, 사진, 노래, 그리고 팟캐스트의 형태로 자신의 디지털 창작물을 배포하기 위해서 그것을 사용한다.",
    },
    7: {
      "title": "자동화와 새로운 일자리",
      "source": "2024년 6월 고2 학평 39번",
      "en": "Imagine that seven out of ten working Americans got fired tomorrow. What would they all do? It's hard to believe you'd have an economy at all if you gave pink slips to more than half the labor force. But that is what the industrial revolution did to the workforce of the early 19th century. Two hundred years ago, 70 percent of American workers lived on the farm. Today automation has eliminated all but 1 percent of their jobs, replacing them with machines. But the displaced workers did not sit idle. Instead, automation created hundreds of millions of jobs in entirely new fields. Those who once farmed were now manning the factories that manufactured farm equipment, cars, and other industrial products. Since then, wave upon wave of new occupations have arrived ─ appliance repair person, food chemist, photographer, web designer ─ each building on previous automation. Today, the vast majority of us are doing jobs that no farmer from the 1800s could have imagined.",
      "ko": "미국인 직장인 10명 중 7명이 내일 해고된다고 상상해 보라. 그들은 모두 무엇을 할까? 노동력의 절반 이상에게 해고 통지서를 보낸다면 경제가 제대로 유지될 것이라고 믿기 어려울 것이다. 하지만 그것은 19세기 초 노동력에 산업 혁명이 했던 것이다. 200년 전, 미국 노동자의 70%가 농사를 지으며 먹고살았다. 오늘날 자동화는 1%를 제외한 모든 일자리를 제거하였고, 그것들을 기계로 대체하였다. 하지만 일자리를 잃은 노동자들은 한가롭게 앉아 있지 않았다. 그 대신, 자동화는 완전히 새로운 분야에서 수억 개의 일자리를 창출했다. 한때 농사를 짓던 사람들은 이제 농기구, 자동차, 그리고 기타 산업 제품을 제조하는 공장에서 일하고 있다. 그 이후로, 가전제품 수리공, 식품 화학자, 사진작가, 웹 디자이너 등 이전의 자동화를 기반으로 한 새로운 직업이 (물결처럼) 계속해서 등장했다. 오늘날, 우리 중 대다수는 1800년대의 농부들은 상상도 할 수 없었던 일을 하고 있다.",
    },
    8: {
      "title": "미조(헤매는 새)의 생태적 중요성",
      "source": "2024년 3월 고2 학평 38번",
      "en": "It is a common assumption that most vagrant birds are ultimately doomed, aside from the rare cases where individuals are able to reorientate and return to their normal ranges. In turn, it is also commonly assumed that vagrancy itself is a relatively unimportant biological phenomenon. This is undoubtedly true for the majority of cases, as the most likely outcome of any given vagrancy event is that the individual will fail to find enough resources, and/or be exposed to inhospitable environmental conditions, and perish. However, there are many lines of evidence to suggest that vagrancy can, on rare occasions, dramatically alter the fate of populations, species or even whole ecosystems. Despite being infrequent, these events can be extremely important when viewed at the timescales over which ecological and evolutionary processes unfold. The most profound consequences of vagrancy relate to the establishment of new breeding sites, new migration routes and wintering locations. Each of these can occur through different mechanisms, and at different frequencies, and they each have their own unique importance.",
      "ko": "무리에서 떨어져 헤매는 대부분의 새들은 방향을 다시 잡고 그들의 일반적인 (서식) 범위로 돌아갈 수 있는 드문 경우의 개체들을 제외하고, 궁극적으로 죽을 운명이라는 것이 일반적인 가정이다. 결국, 무리에서 떨어져 헤매는 것 자체가 비교적 중요하지 않은 생물학적 현상이라고 일반적으로 여겨지기도 한다. 이것은 의심할 여지없이 대부분의 경우에 사실인데, 무리에서 떨어져 헤매는 어떤 경우든 가장 가능성 있는 결과는 개체가 충분한 자원을 찾지 못하고/못하거나, 살기 힘든 환경 조건에 노출되어 죽기 때문이다. 하지만 드문 경우에, 무리에서 떨어져 헤매는 것이 개체 수, 종, 심지어 생태계 전체의 운명을 극적으로 바꿀 수 있다는 것을 시사하는 많은 증거가 있다. 드물기는 하지만, 이러한 경우들은 생태학적이고 진화적인 과정이 진행되는 시간의 관점에서 볼 때 매우 중요할 수 있다. 무리에서 떨어져 헤매는 것의 가장 중대한 결과는 새로운 번식지, 새로운 이동 경로 및 월동 장소의 확보와 관련이 있다. 이들 각각은 서로 다른 메커니즘을 통해, 서로 다른 빈도로 발생할 수 있으며, 각각 고유한 중요성을 가지고 있다.",
    },
  },
  "19": {
    1: {
      "title": "체지방 축적 vs 식량 저장",
      "source": "2025년 9월 고2 학평 41~42번(장문)",
      "en": "Many animals pursue a mixed strategy of accumulating both body fat and food, which leads one to ask, \"What are the relative advantages and disadvantages of these two forms of energy storage?\" Maximum fat deposition increases with body mass whereas maximum food storage is not constrained by body size. This means that animals, especially small animals, can accumulate much greater energy reserves in the form of stored food than they can in the form of body fat. Further, stored food is more economical than body fat because fat contributes to body mass, and metabolic rate increases with body mass. In other words, there is a metabolic expense to maintaining fat. Excessive fat accumulations may also have a negative effect on an animal's ability to avoid predators. And, if maintaining a high body temperature is advantageous, animals might be expected to accumulate more energy in the form of a food store than as body fat. On the other hand, stored food may rot over time, may be removed by robbers, or may simply be lost. Many animals must expend energy managing and protecting their food stores. Eating food and converting it to fat reduces these types of losses and the energetic costs of managing stored food. A large accumulation of body fat adds to an animal's fasting capacity, especially large animals, permitting some animals to enter prolonged dormancy in the relative security of a hibernaculum. Thus, both fat accumulation and food storage have some decided advantages.",
      "ko": "많은 동물이 체지방과 식량 둘 다 축적하는 혼합 전략을 추구하는데, 이는 우리가 '이 두 가지 에너지 저장 형태의 상대적인 장단점은 무엇인가?'라고 질문하게 한다. 최대 지방 축적량은 체질량에 따라 증가하는 반면 최대 식량 저장량은 신체 크기에 제한을 받지 않는다. 이는 동물, 특히 작은 동물은 그들이 체지방 형태로 축적할 수 있는 것보다 훨씬 더 많은 에너지 비축량을 저장된 식량의 형태로 축적할 수 있다는 것을 의미한다. 게다가, 지방은 체질량에 기여하고, 신진대사율도 체질량에 따라 높아지기 때문에 저장된 식량은 체지방보다 더 경제적이다. 다시 말해, 체지방을 유지하는 데에는 신진대사 비용이 든다. 과도한 체지방 축적은 또한 포식자를 피하는 동물의 능력에 부정적인 영향을 미칠지도 모른다. 그리고 만약 높은 체온을 유지하는 것이 유리하다면, 동물은 체지방보다 저장된 식량의 형태로 더 많은 에너지를 축적할 것으로 예상될 수 있다. 반면에 저장된 식량은 시간이 지남에 따라 상하거나, 도둑에 의해 제거되거나 단순히 분실될 수 있다. 많은 동물은 저장된 식량을 관리하고 보호하는 데 에너지를 소비해야 한다. 식량을 먹고 그것을 지방으로 전환하는 것은 이러한 유형의 손실과 저장된 식량을 관리하는 데 드는 에너지 비용을 줄인다. 체지방의 많은 축적은 동물의 금식 능력을 높여 주는데, 특히 큰 동물에게 그러하며, 이는 일부 동물들이 동면 장소의 상대적인 안전함 속에서 장기간의 휴면 상태에 들게 해 준다. 따라서 지방 축적과 식량 저장 둘 다 몇 가지 결정적인 이점이 있다.",
    },
  },
}
